# Generated by Django 4.2.7 on 2025-11-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_user_auth_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='category',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='feed_title',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='image',
        ),
    ]
