# Generated by Django 4.2.7 on 2025-11-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_feed_category_remove_feed_feed_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Event/images'),
        ),
    ]
