# Generated by Django 4.2.7 on 2025-11-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_feed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='media/userimage/img4.png', upload_to='media/userimage'),
        ),
    ]
